In [7]:
from data.loader import NuSceneDataset
from utils import default_collate
from torch.utils.data import DataLoader

nuscenes_data = NuSceneDataset(root_dir="data")

data_loader = DataLoader(nuscenes_data,
                         batch_size=64,
                         shuffle=True,
                         collate_fn=default_collate)

In [41]:
from pandas import DataFrame
data = next(iter(data_loader))
data["rel_past"].numpy()[:, 0][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [42]:
data["rel_past"].numpy()[:, 0][1]

array([ 4.2316895e+00,  8.2702637e-02,  0.0000000e+00,  4.5299530e-06,
        9.4156899e-04, -3.2212916e-03,  5.7160947e-04,  6.1536312e-01,
       -1.2942448e-02,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00], dtype=float32)

In [43]:
data["rel_past"].numpy()[:, 0][2]

array([ 4.0914307e+00,  6.6101074e-02,  0.0000000e+00, -4.0531158e-05,
       -2.7119545e-03, -1.5746779e-04,  5.8813021e-06,  4.0565014e-01,
       -3.4774125e-02,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00], dtype=float32)

In [44]:
data["rel_past"].numpy()[:, 0][3]

array([3.8164062e+00, 7.2570801e-02, 0.0000000e+00, 9.2387199e-06,
       1.0222616e-03, 2.0045156e-03, 7.5024087e-04, 1.1745739e-01,
       3.0692101e-02, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00], dtype=float32)